import { db } from '@/db';
import { testParts, questions } from '@/db/schema';

async function main() {
    // Test 34 - IELTS Reading Practice Test 1
    const test34Parts = [
        {
            testId: 34,
            partNumber: 1,
            title: 'Reading Passage 1',
            instructions: 'You should spend about 20 minutes on Questions 1-13, which are based on Reading Passage 1 below.',
            content: `The Evolution of Artificial Intelligence: From Theory to Practice

The concept of artificial intelligence has captivated human imagination for decades, evolving from science fiction fantasies into tangible technological realities that permeate our daily lives. The journey of AI development represents one of the most significant technological revolutions of the modern era, fundamentally transforming how we interact with machines and process information.

The theoretical foundations of artificial intelligence were established in the mid-20th century by pioneering computer scientists and mathematicians. Alan Turing, often regarded as the father of modern computing, proposed the famous Turing Test in 1950 as a benchmark for machine intelligence. This test evaluates whether a machine can engage in conversations indistinguishable from those of a human being. Turing's vision laid the groundwork for subsequent AI research and development.

During the 1950s and 1960s, researchers made significant strides in developing early AI systems. The Logic Theorist, created by Allen Newell and Herbert Simon in 1956, was among the first programs to demonstrate automated reasoning capabilities. This breakthrough marked the beginning of symbolic AI, which relied on logical rules and knowledge representation to solve problems. Researchers believed that by encoding human knowledge into computer programs, they could create machines capable of intelligent behavior.

However, the initial optimism surrounding AI development was soon tempered by practical limitations. The computational resources available during the early decades were insufficient to support complex AI applications. Moreover, researchers discovered that many cognitive tasks, which humans perform effortlessly, proved extraordinarily difficult to program into machines. This realization led to what became known as the "AI winter" – periods of reduced funding and diminished interest in AI research.

The resurgence of AI began in the 1980s with the development of expert systems, computer programs designed to emulate the decision-making abilities of human specialists in specific domains. These systems incorporated extensive knowledge bases and inference engines to provide solutions to complex problems in fields such as medicine, finance, and engineering. Companies invested heavily in expert systems, recognizing their potential to automate specialized tasks and reduce dependency on human expertise.

The most transformative period in AI development commenced in the 21st century with the emergence of machine learning and deep learning technologies. Unlike traditional symbolic AI, these approaches enable machines to learn patterns from data without explicit programming. Neural networks, inspired by the structure and function of biological brains, became the foundation for breakthrough applications in image recognition, natural language processing, and predictive analytics.

The availability of massive datasets and unprecedented computational power facilitated rapid advances in AI capabilities. Cloud computing platforms provided researchers and developers with access to powerful hardware resources, while the internet generated enormous quantities of data necessary for training sophisticated AI models. These technological convergences created an environment conducive to AI innovation and commercialization.

Contemporary AI applications demonstrate remarkable versatility across diverse industries. In healthcare, AI systems assist physicians in diagnosing diseases, analyzing medical images, and developing personalized treatment plans. Financial institutions employ AI algorithms for fraud detection, risk assessment, and algorithmic trading. Transportation companies utilize AI for route optimization and autonomous vehicle development. Entertainment platforms leverage AI to recommend content and enhance user experiences.

Despite these achievements, artificial intelligence continues to face significant challenges and ethical considerations. Issues related to algorithmic bias, privacy protection, and job displacement remain contentious topics requiring careful examination. Researchers and policymakers must collaborate to establish frameworks ensuring responsible AI development and deployment.

The future trajectory of artificial intelligence appears promising yet uncertain. Emerging technologies such as quantum computing may unlock new possibilities for AI advancement, while concerns about artificial general intelligence raise questions about long-term implications for humanity. As AI systems become increasingly sophisticated, society must navigate the balance between technological progress and ethical responsibility, ensuring that artificial intelligence serves the collective benefit of humankind.`,
            audioUrl: null,
            listeningScript: null
        },
        {
            testId: 34,
            partNumber: 2,
            title: 'Reading Passage 2',
            instructions: 'You should spend about 20 minutes on Questions 14-27, which are based on Reading Passage 2 below.',
            content: `Climate Change: Understanding the Global Challenge and Response Strategies

Climate change represents one of the most pressing environmental challenges facing humanity in the 21st century. The overwhelming scientific consensus confirms that human activities, particularly the emission of greenhouse gases, are driving unprecedented changes in Earth's climate system. These modifications manifest through rising global temperatures, shifting precipitation patterns, melting ice sheets, and increasingly frequent extreme weather events that threaten ecosystems, human settlements, and economic stability worldwide.

The greenhouse effect, while naturally occurring and essential for sustaining life on Earth, has been significantly amplified by human industrial activities since the Industrial Revolution. Carbon dioxide, methane, nitrous oxide, and other greenhouse gases trap heat in the atmosphere, creating a warming effect that has intensified dramatically over the past century. Atmospheric carbon dioxide concentrations have increased by more than 40% since pre-industrial times, primarily due to fossil fuel combustion, deforestation, and industrial processes.

Temperature records maintained by meteorological organizations worldwide provide compelling evidence of global warming trends. The past decade includes the warmest years on record, with average global temperatures rising approximately 1.1 degrees Celsius above pre-industrial levels. This seemingly modest increase has profound implications for climate systems, as even small temperature changes can trigger cascading effects throughout the environment.

Arctic regions experience the most dramatic impacts of climate change, with temperatures rising at twice the global average rate. Arctic sea ice extent has declined substantially, with satellite observations revealing a loss of approximately 13% per decade since the late 1970s. The melting of glaciers and ice sheets contributes to sea level rise, threatening coastal communities and low-lying island nations. Permafrost thaw releases stored carbon into the atmosphere, creating positive feedback loops that accelerate warming.

Ocean systems play a crucial role in climate regulation, absorbing approximately 30% of human-produced carbon dioxide and 90% of excess heat generated by greenhouse gas emissions. However, this absorption comes at a cost. Ocean acidification, often termed "the other CO2 problem," occurs as seawater absorbs carbon dioxide, forming carbonic acid that lowers ocean pH levels. This acidification threatens marine ecosystems, particularly organisms with calcium carbonate shells and skeletons, including corals, shellfish, and certain plankton species.

Precipitation patterns are shifting globally, with some regions experiencing increased rainfall and flooding while others face prolonged droughts. These changes affect agricultural productivity, water resource availability, and natural disaster frequency. Extreme weather events, including hurricanes, heat waves, and wildfires, are becoming more intense and frequent, causing significant economic losses and human suffering.

Biodiversity faces unprecedented threats as climate change alters habitats faster than many species can adapt. Range shifts, phenological mismatches, and ecosystem disruptions challenge conservation efforts and threaten food webs. Coral bleaching events, driven by elevated ocean temperatures, have devastated reef ecosystems worldwide, eliminating crucial habitat for countless marine species.

International cooperation has emerged as essential for addressing climate change effectively. The Paris Agreement, adopted in 2015, represents the most comprehensive global effort to limit greenhouse gas emissions and prevent dangerous climate change. Nearly 200 countries committed to keeping global temperature increases well below 2 degrees Celsius above pre-industrial levels, with efforts to limit increases to 1.5 degrees Celsius.

Mitigation strategies focus on reducing greenhouse gas emissions through various approaches. Renewable energy technologies, including solar, wind, and hydroelectric power, offer alternatives to fossil fuels for electricity generation. Energy efficiency improvements in buildings, transportation, and industrial processes can significantly reduce emissions while providing economic benefits. Carbon pricing mechanisms, such as carbon taxes and cap-and-trade systems, create economic incentives for emission reductions.

Adaptation measures help communities prepare for and respond to climate change impacts that cannot be prevented. These strategies include infrastructure modifications, ecosystem restoration, agricultural adjustments, and disaster preparedness planning. Coastal protection systems, drought-resistant crops, and early warning systems exemplify adaptation approaches being implemented worldwide.

Individual actions, while important, must be complemented by systemic changes to achieve meaningful climate progress. Personal choices regarding energy consumption, transportation, diet, and consumption patterns contribute to collective emission reductions. However, transformational change requires policy reforms, technological innovations, and business model adaptations across all sectors of society.

The economic implications of climate change are substantial, with potential costs reaching trillions of dollars globally if mitigation efforts prove inadequate. Conversely, investments in clean technologies and sustainable practices offer opportunities for economic growth, job creation, and improved quality of life. The transition to a low-carbon economy presents both challenges and opportunities for businesses, governments, and individuals worldwide.`,
            audioUrl: null,
            listeningScript: null
        },
        {
            testId: 34,
            partNumber: 3,
            title: 'Reading Passage 3',
            instructions: 'You should spend about 20 minutes on Questions 28-40, which are based on Reading Passage 3 below.',
            content: `Ancient Civilizations: Unraveling the Mysteries of Human Development

The study of ancient civilizations provides invaluable insights into human development, revealing the remarkable achievements and complex societies that emerged thousands of years before the modern era. Archaeological discoveries and historical research continue to illuminate the sophisticated cultures that laid the foundations for contemporary civilization, demonstrating humanity's enduring capacity for innovation, organization, and cultural expression across diverse geographical and temporal contexts.

Mesopotamia, often referred to as the "cradle of civilization," witnessed the emergence of the world's first urban centers around 3500 BCE. The Sumerians developed revolutionary technologies and social institutions that would influence subsequent civilizations for millennia. Their invention of cuneiform writing, one of humanity's earliest writing systems, enabled the recording of laws, literature, and commercial transactions, fundamentally transforming human communication and knowledge preservation.

The Code of Hammurabi, established around 1750 BCE in Babylon, represents one of the earliest comprehensive legal systems, comprising 282 laws that governed various aspects of society including trade, family relationships, and criminal justice. This legal framework demonstrated sophisticated understanding of social organization and established precedents for legal systems that continue to influence modern jurisprudence.

Egyptian civilization, flourishing along the Nile River for over three millennia, achieved remarkable accomplishments in architecture, medicine, mathematics, and astronomy. The construction of pyramids at Giza showcases extraordinary engineering capabilities, with the Great Pyramid originally standing 146 meters tall and containing approximately 2.3 million stone blocks, each weighing between 2.5 and 15 tons. The precision of pyramid construction, with base measurements accurate to within 2 centimeters, reflects advanced mathematical and surveying knowledge.

Egyptian medical practices, documented in papyrus texts such as the Edwin Smith Papyrus and the Ebers Papyrus, reveal sophisticated understanding of anatomy, surgery, and pharmacology. Ancient Egyptian physicians performed complex surgical procedures, including brain surgery and cataract removal, while developing treatments for various ailments using natural remedies and medicinal compounds.

The Indus Valley Civilization, spanning modern-day Pakistan and northwestern India from approximately 2600 to 1900 BCE, demonstrated remarkable urban planning capabilities. Cities like Harappa and Mohenjo-daro featured sophisticated drainage systems, standardized brick construction, and carefully planned street layouts with uniform building materials and architectural styles. The civilization's standardized weights and measures system facilitated extensive trade networks extending from Central Asia to Mesopotamia.

Ancient China's contributions to human civilization include numerous technological innovations that revolutionized daily life and communication. The invention of paper around 100 CE democratized information recording and dissemination, while the development of gunpowder, the compass, and printing technology transformed warfare, navigation, and knowledge distribution. Chinese astronomical observations, meticulously recorded over centuries, provided accurate calendars and contributed to understanding celestial phenomena.

The philosophical traditions established in ancient China, including Confucianism, Taoism, and Legalism, profoundly influenced social organization, governance, and ethical frameworks throughout East Asia. Confucian emphasis on education, social harmony, and moral cultivation shaped educational systems and governmental structures that persist in modified forms today.

Greek civilization's intellectual achievements laid the foundation for Western philosophy, science, and democratic governance. Ancient Greek philosophers, including Socrates, Plato, and Aristotle, developed systematic approaches to logic, ethics, and natural philosophy that continue to influence contemporary thought. The scientific method, mathematical proofs, and empirical observation techniques pioneered by Greek scholars established methodological frameworks for modern scientific inquiry.

Greek mathematical achievements, exemplified by Euclid's geometric principles and Archimedes' contributions to physics and engineering, provided essential tools for technological advancement. The concept of democracy, first implemented in Athens during the 5th century BCE, introduced principles of citizen participation and representative governance that inspire modern democratic systems worldwide.

Roman civilization synthesized and expanded upon the achievements of earlier cultures while developing distinctive contributions to law, engineering, and administration. Roman law, codified in the Corpus Juris Civilis, established legal principles that form the basis for many contemporary legal systems. The concept of citizenship, initially limited but gradually expanded, created frameworks for social integration and political participation.

Roman engineering accomplishments, including extensive road networks, aqueduct systems, and architectural innovations like concrete construction and arch-supported structures, facilitated urbanization and economic development across the empire. The Roman road system, spanning over 250,000 miles at its peak, enabled efficient communication, trade, and military deployment throughout the Mediterranean world.

Archaeological methodologies have revolutionized understanding of ancient civilizations through systematic excavation, artifact analysis, and interdisciplinary research approaches. Carbon dating, stratigraphy, and remote sensing technologies enable precise chronological placement and spatial analysis of archaeological sites. Digital reconstruction techniques and computer modeling provide new perspectives on ancient architecture, urban planning, and daily life.

Contemporary research continues to reveal previously unknown aspects of ancient civilizations, challenging traditional narratives and expanding understanding of human cultural diversity. Recent discoveries, including advanced agricultural systems, sophisticated astronomical observations, and complex trade networks, demonstrate that ancient societies possessed knowledge and capabilities often underestimated by earlier scholarship.

The legacy of ancient civilizations permeates modern society through institutional structures, technological innovations, artistic traditions, and philosophical frameworks. Understanding these historical foundations provides essential context for addressing contemporary challenges and appreciating the continuity of human achievement across millennia. As archaeological research advances and new discoveries emerge, our comprehension of ancient civilizations continues to evolve, revealing the remarkable complexity and sophistication of humanity's earliest organized societies.`
        }
    ];

    const test34Questions = [
        // Part 1 Questions (1-13)
        { partId: 1, questionNumber: 1, questionText: 'Alan Turing proposed the Turing Test in 1950.', questionType: 'true_false_not_given', options: null, correctAnswer: 'TRUE', marks: 1 },
        { partId: 1, questionNumber: 2, questionText: 'The Logic Theorist was the first AI program ever created.', questionType: 'true_false_not_given', options: null, correctAnswer: 'FALSE', marks: 1 },
        { partId: 1, questionNumber: 3, questionText: 'Early AI research faced limitations due to insufficient computational resources.', questionType: 'true_false_not_given', options: null, correctAnswer: 'TRUE', marks: 1 },
        { partId: 1, questionNumber: 4, questionText: 'Expert systems were developed in the:', questionType: 'multiple_choice', options: JSON.stringify(['A) 1950s', 'B) 1960s', 'C) 1980s', 'D) 1990s']), correctAnswer: 'C', marks: 1 },
        { partId: 1, questionNumber: 5, questionText: 'Which factor contributed most to AI advancement in the 21st century?', questionType: 'multiple_choice', options: JSON.stringify(['A) Government funding', 'B) Machine learning and deep learning', 'C) Expert systems', 'D) Symbolic AI']), correctAnswer: 'B', marks: 1 },
        { partId: 1, questionNumber: 6, questionText: 'Neural networks are inspired by _______ brains.', questionType: 'gap_fill', options: null, correctAnswer: 'biological', marks: 1 },
        { partId: 1, questionNumber: 7, questionText: 'Cloud computing platforms provided access to powerful _______ resources.', questionType: 'gap_fill', options: null, correctAnswer: 'hardware', marks: 1 },
        { partId: 1, questionNumber: 8, questionText: 'In healthcare, AI assists with diagnosing diseases and analyzing _______ images.', questionType: 'gap_fill', options: null, correctAnswer: 'medical', marks: 1 },
        { partId: 1, questionNumber: 9, questionText: 'Financial institutions use AI for fraud detection and _______ assessment.', questionType: 'gap_fill', options: null, correctAnswer: 'risk', marks: 1 },
        { partId: 1, questionNumber: 10, questionText: 'Algorithmic bias is mentioned as a challenge for AI development.', questionType: 'true_false_not_given', options: null, correctAnswer: 'TRUE', marks: 1 },
        { partId: 1, questionNumber: 11, questionText: 'Quantum computing is currently being used in AI systems.', questionType: 'true_false_not_given', options: null, correctAnswer: 'NOT GIVEN', marks: 1 },
        { partId: 1, questionNumber: 12, questionText: 'The passage suggests AI development should prioritize:', questionType: 'multiple_choice', options: JSON.stringify(['A) Speed of advancement', 'B) Commercial success', 'C) Ethical responsibility', 'D) Cost reduction']), correctAnswer: 'C', marks: 1 },
        { partId: 1, questionNumber: 13, questionText: 'Complete the sentence: The future of AI requires balancing technological progress with _______ responsibility.', questionType: 'gap_fill', options: null, correctAnswer: 'ethical', marks: 1 },

        // Part 2 Questions (14-27)
        { partId: 2, questionNumber: 14, questionText: 'Choose the correct heading for paragraph 2:', questionType: 'matching_headings', options: JSON.stringify(['i) The greenhouse effect explanation', 'ii) Temperature rise evidence', 'iii) Arctic impact assessment', 'iv) Ocean system changes']), correctAnswer: 'i', marks: 1 },
        { partId: 2, questionNumber: 15, questionText: 'Choose the correct heading for paragraph 4:', questionType: 'matching_headings', options: JSON.stringify(['i) Global temperature records', 'ii) Arctic climate impacts', 'iii) Industrial emission sources', 'iv) Sea level predictions']), correctAnswer: 'ii', marks: 1 },
        { partId: 2, questionNumber: 16, questionText: 'Choose the correct heading for paragraph 6:', questionType: 'matching_headings', options: JSON.stringify(['i) Agricultural challenges', 'ii) Precipitation pattern changes', 'iii) Economic implications', 'iv) Biodiversity threats']), correctAnswer: 'ii', marks: 1 },
        { partId: 2, questionNumber: 17, questionText: 'Atmospheric CO2 has increased by more than _______ since pre-industrial times.', questionType: 'sentence_completion', options: null, correctAnswer: '40%', marks: 1 },
        { partId: 2, questionNumber: 18, questionText: 'Global temperatures have risen approximately _______ degrees Celsius above pre-industrial levels.', questionType: 'sentence_completion', options: null, correctAnswer: '1.1', marks: 1 },
        { partId: 2, questionNumber: 19, questionText: 'Arctic sea ice extent has declined by approximately _______ per decade.', questionType: 'sentence_completion', options: null, correctAnswer: '13%', marks: 1 },
        { partId: 2, questionNumber: 20, questionText: 'Oceans absorb _______ of human-produced carbon dioxide.', questionType: 'sentence_completion', options: null, correctAnswer: '30%', marks: 1 },
        { partId: 2, questionNumber: 21, questionText: 'What is the main cause of ocean acidification?', questionType: 'multiple_choice', options: JSON.stringify(['A) Industrial pollution', 'B) Plastic waste', 'C) CO2 absorption', 'D) Oil spills']), correctAnswer: 'C', marks: 1 },
        { partId: 2, questionNumber: 22, questionText: 'The Paris Agreement was adopted in:', questionType: 'multiple_choice', options: JSON.stringify(['A) 2014', 'B) 2015', 'C) 2016', 'D) 2017']), correctAnswer: 'B', marks: 1 },
        { partId: 2, questionNumber: 23, questionText: 'How many countries committed to the Paris Agreement?', questionType: 'multiple_choice', options: JSON.stringify(['A) Nearly 100', 'B) Nearly 150', 'C) Nearly 200', 'D) Over 200']), correctAnswer: 'C', marks: 1 },
        { partId: 2, questionNumber: 24, questionText: 'The target temperature increase limit is well below _______ degrees Celsius.', questionType: 'sentence_completion', options: null, correctAnswer: '2', marks: 1 },
        { partId: 2, questionNumber: 25, questionText: 'Carbon pricing mechanisms include carbon taxes and _______ systems.', questionType: 'sentence_completion', options: null, correctAnswer: 'cap-and-trade', marks: 1 },
        { partId: 2, questionNumber: 26, questionText: 'Individual actions must be complemented by _______ changes for meaningful progress.', questionType: 'sentence_completion', options: null, correctAnswer: 'systemic', marks: 1 },
        { partId: 2, questionNumber: 27, questionText: 'The transition to a low-carbon economy presents both challenges and _______.', questionType: 'sentence_completion', options: null, correctAnswer: 'opportunities', marks: 1 },

        // Part 3 Questions (28-40)
        { partId: 3, questionNumber: 28, questionText: 'Mesopotamia is known as the "cradle of civilization" because:', questionType: 'multiple_choice', options: JSON.stringify(['A) It had the largest population', 'B) It was the most advanced militarily', 'C) It had the first urban centers', 'D) It invented agriculture']), correctAnswer: 'C', marks: 1 },
        { partId: 3, questionNumber: 29, questionText: 'The Code of Hammurabi contained how many laws?', questionType: 'multiple_choice', options: JSON.stringify(['A) 182', 'B) 282', 'C) 382', 'D) 482']), correctAnswer: 'B', marks: 1 },
        { partId: 3, questionNumber: 30, questionText: 'The Great Pyramid originally stood _______ meters tall.', questionType: 'gap_fill', options: null, correctAnswer: '146', marks: 1 },
        { partId: 3, questionNumber: 31, questionText: 'Each pyramid stone block weighed between _______ and 15 tons.', questionType: 'gap_fill', options: null, correctAnswer: '2.5', marks: 1 },
        { partId: 3, questionNumber: 32, questionText: 'The Indus Valley Civilization existed from approximately:', questionType: 'multiple_choice', options: JSON.stringify(['A) 3600 to 2900 BCE', 'B) 2600 to 1900 BCE', 'C) 1600 to 900 BCE', 'D) 1000 to 500 BCE']), correctAnswer: 'B', marks: 1 },
        { partId: 3, questionNumber: 33, questionText: 'Paper was invented in China around _______ CE.', questionType: 'gap_fill', options: null, correctAnswer: '100', marks: 1 },
        { partId: 3, questionNumber: 34, questionText: 'Match the civilization with its contribution:', questionType: 'matching', options: JSON.stringify(['A) Mesopotamia - Democracy', 'B) Egypt - Paper invention', 'C) Greece - Cuneiform writing', 'D) China - Compass']), correctAnswer: 'D', marks: 1 },
        { partId: 3, questionNumber: 35, questionText: 'Match the civilization with its contribution:', questionType: 'matching', options: JSON.stringify(['A) Greece - Pyramid construction', 'B) Rome - Democratic principles', 'C) Egypt - Medical practices', 'D) China - Legal codes']), correctAnswer: 'C', marks: 1 },
        { partId: 3, questionNumber: 36, questionText: 'The Roman road system spanned over _______ miles at its peak.', questionType: 'gap_fill', options: null, correctAnswer: '250,000', marks: 1 },
        { partId: 3, questionNumber: 37, questionText: 'Which dating method is mentioned for archaeological research?', questionType: 'multiple_choice', options: JSON.stringify(['A) Tree ring dating', 'B) Carbon dating', 'C) Potassium dating', 'D) Uranium dating']), correctAnswer: 'B', marks: 1 },
        { partId: 3, questionNumber: 38, questionText: 'Digital reconstruction techniques provide new perspectives on ancient _______.', questionType: 'gap_fill', options: null, correctAnswer: 'architecture', marks: 1 },
        { partId: 3, questionNumber: 39, questionText: 'Recent discoveries have revealed advanced _______ systems in ancient civilizations.', questionType: 'gap_fill', options: null, correctAnswer: 'agricultural', marks: 1 },
        { partId: 3, questionNumber: 40, questionText: 'Archaeological research continues to reveal the _______ and sophistication of ancient societies.', questionType: 'gap_fill', options: null, correctAnswer: 'complexity', marks: 1 }
    ];

    // Test 35 - IELTS Reading Practice Test 2
    const test35Parts = [
        {
            testId: 35,
            partNumber: 1,
            title: 'Reading Passage 1',
            instructions: 'You should spend about 20 minutes on Questions 1-13, which are based on Reading Passage 1 below.',
            content: `Renewable Energy: The Sustainable Path to Global Energy Security

The transition from fossil fuels to renewable energy sources represents one of the most significant technological and economic transformations of the 21st century. As concerns about climate change intensify and fossil fuel reserves diminish, nations worldwide are investing heavily in renewable energy technologies that harness natural processes to generate clean, sustainable power. This fundamental shift in energy production methodology promises to reshape global economic structures, environmental policies, and geopolitical relationships while addressing the urgent need for carbon emission reductions.

Solar energy technology has experienced remarkable advancement and cost reduction over the past two decades. Photovoltaic solar panels, which convert sunlight directly into electricity through semiconductor materials, have become increasingly efficient and affordable. The cost of solar electricity has declined by approximately 85% since 2010, making solar power competitive with traditional fossil fuel sources in many regions. Large-scale solar installations, including concentrated solar power plants that use mirrors to focus sunlight for thermal energy generation, can produce hundreds of megawatts of electricity while occupying relatively small land areas.

Wind energy represents another rapidly expanding renewable sector, with both onshore and offshore wind farms contributing substantially to global electricity generation. Modern wind turbines, standing up to 150 meters tall with blade spans exceeding 100 meters, can generate between 2 and 15 megawatts of power depending on their design and wind conditions. Offshore wind installations offer particular advantages, including stronger and more consistent wind resources, reduced visual impact on landscapes, and proximity to coastal population centers where electricity demand is typically highest.

Hydroelectric power, while not a new technology, continues to evolve through innovative approaches including small-scale run-of-river systems and pumped-storage facilities that provide grid stability and energy storage capabilities. Traditional large-scale hydroelectric dams generate approximately 16% of global electricity, but environmental concerns regarding ecosystem disruption and river flow modification have encouraged development of less intrusive alternatives. Micro-hydroelectric systems can generate power for remote communities without requiring massive infrastructure investments or significant environmental modifications.

Geothermal energy utilizes heat from the Earth's interior to generate electricity and provide direct heating applications. Enhanced geothermal systems, which inject water into hot dry rock formations to create steam for power generation, expand geothermal potential beyond traditional volcanic regions. Iceland demonstrates geothermal energy's potential, deriving approximately 25% of its electricity and 90% of its heating from geothermal sources while maintaining some of the world's lowest electricity costs.

Biomass energy, derived from organic materials including agricultural waste, forestry residues, and dedicated energy crops, offers carbon-neutral electricity generation when managed sustainably. Advanced biomass technologies, such as gasification and pyrolysis, convert organic matter into synthetic fuels and chemicals while capturing carbon dioxide for storage or utilization. However, biomass energy requires careful management to avoid competition with food production and prevent deforestation or habitat destruction.

Energy storage technologies play a crucial role in renewable energy integration, addressing the intermittent nature of solar and wind power generation. Lithium-ion battery systems have experienced dramatic cost reductions and performance improvements, enabling utility-scale energy storage installations that can store excess renewable energy during peak production periods and release it when demand exceeds generation. Alternative storage technologies, including compressed air energy storage, pumped hydro storage, and emerging hydrogen fuel systems, provide additional options for grid-scale energy management.

Smart grid technologies facilitate renewable energy integration by enabling bidirectional communication between electricity generators, storage systems, and consumers. Advanced metering infrastructure allows real-time monitoring of electricity consumption and production, optimizing grid operations and reducing waste. Demand response programs encourage consumers to adjust electricity usage patterns to match renewable energy availability, improving overall system efficiency and reducing reliance on backup fossil fuel generation.

The economic implications of renewable energy adoption extend beyond electricity generation to encompass job creation, industrial development, and energy security benefits. The renewable energy sector employs millions of workers globally in manufacturing, installation, maintenance, and support services. Countries investing in renewable energy technologies often develop competitive advantages in emerging markets while reducing dependence on fossil fuel imports and price volatility.

Government policies and international cooperation play essential roles in accelerating renewable energy deployment. Feed-in tariffs, renewable portfolio standards, tax incentives, and carbon pricing mechanisms create favorable economic conditions for renewable energy investments. International technology transfer programs and climate finance initiatives help developing countries access renewable energy technologies and build local capacity for sustainable energy development.

Despite significant progress, renewable energy faces ongoing challenges including grid integration complexities, energy storage costs, and policy uncertainties. The variability of solar and wind resources requires sophisticated forecasting and grid management systems to maintain reliable electricity supply. Rural and remote areas often lack the infrastructure necessary for large-scale renewable energy integration, requiring innovative distributed generation solutions.

The future of renewable energy appears increasingly promising as technological advances continue to improve efficiency and reduce costs. Emerging technologies, including perovskite solar cells, floating offshore wind platforms, and advanced energy storage systems, offer potential for further performance enhancements. As renewable energy technologies mature and scale up globally, they promise to deliver the clean, sustainable energy systems necessary for addressing climate change while supporting continued economic development and improved quality of life for billions of people worldwide.`,
            audioUrl: null,
            listeningScript: null
        },
        {
            testId: 35,
            partNumber: 2,
            title: 'Reading Passage 2',
            instructions: 'You should spend about 20 minutes on Questions 14-27, which are based on Reading Passage 2 below.',
            content: `Cognitive Psychology: Understanding the Mechanisms of Human Thought

Cognitive psychology emerged as a dominant paradigm in psychological research during the mid-20th century, fundamentally transforming our understanding of mental processes and human behavior. This scientific discipline investigates how people perceive, process, store, and retrieve information, examining the complex mechanisms underlying learning, memory, attention, language, problem-solving, and decision-making. By applying rigorous experimental methodologies and theoretical frameworks, cognitive psychologists have revealed the intricate workings of the human mind, providing insights that influence education, technology design, clinical practice, and artificial intelligence development.

The cognitive revolution began in the 1950s as psychologists moved beyond behaviorist approaches that focused exclusively on observable behaviors, recognizing the importance of internal mental processes in understanding human actions. Pioneering researchers like George Miller, Ulric Neisser, and Jerome Bruner established cognitive psychology as a legitimate scientific field by developing innovative experimental techniques and theoretical models that made mental processes accessible to empirical investigation.

Memory research represents one of cognitive psychology's most extensively studied domains, revealing the multi-faceted nature of human information storage and retrieval systems. The modal model of memory, proposed by Atkinson and Shiffrin in 1968, describes memory as comprising three distinct stores: sensory memory, short-term memory, and long-term memory. Sensory memory briefly retains incoming sensory information for milliseconds to seconds, allowing the cognitive system to process relevant stimuli while filtering out unnecessary details.

Short-term memory, with its limited capacity of approximately seven items and duration of 15-30 seconds without rehearsal, serves as a temporary workspace for active information processing. Working memory, an expanded conceptualization developed by Alan Baddeley, incorporates executive control processes that manipulate and coordinate information from multiple sources. The working memory model includes specialized subsystems: the phonological loop for verbal and acoustic information, the visuospatial sketchpad for visual and spatial data, and the central executive that coordinates these subsystems while controlling attention and strategic processing.

Long-term memory encompasses vast stores of knowledge, experiences, and skills accumulated throughout an individual's lifetime. Cognitive researchers distinguish between explicit memory, which involves conscious recollection of facts and events, and implicit memory, which influences behavior without conscious awareness. Episodic memory stores personally experienced events with temporal and contextual details, while semantic memory contains general knowledge about the world, including concepts, facts, and meanings independent of specific learning episodes.

Attention mechanisms determine which information receives processing priority in the cognitively demanding environment humans navigate daily. Selective attention enables focus on relevant stimuli while ignoring distractions, though this filtering process operates imperfectly, as demonstrated by phenomena like the cocktail party effect, where personally relevant information can capture attention despite attempts to focus elsewhere. Divided attention studies reveal limitations in simultaneously processing multiple information streams, though practice and expertise can improve multitasking performance in specific domains.

Language processing represents perhaps the most uniquely human cognitive ability, involving complex interactions between phonological, syntactic, semantic, and pragmatic systems. Psycholinguistic research has identified distinct processing stages in language comprehension, from initial acoustic or visual pattern recognition through syntactic parsing and semantic interpretation to pragmatic inference about speaker intentions. The modularity debate addresses whether language processing occurs through specialized, independent modules or integrated systems sharing cognitive resources with other mental processes.

Problem-solving and reasoning research examines how people approach novel challenges and draw logical conclusions from available information. Studies of expert-novice differences reveal that expertise involves more than accumulated knowledge, encompassing sophisticated pattern recognition abilities, efficient problem representation strategies, and domain-specific processing techniques. Heuristics and biases research, pioneered by Daniel Kahneman and Amos Tversky, demonstrates systematic deviations from rational decision-making, revealing cognitive shortcuts that often produce accurate judgments but can lead to predictable errors in specific contexts.

Cognitive development research, influenced by Jean Piaget's seminal work, investigates how thinking processes change throughout the lifespan. Contemporary developmental cognitive psychology emphasizes both universal developmental patterns and individual differences in cognitive growth, examining how biological maturation, environmental experiences, and cultural factors interact to shape cognitive abilities. Executive functions, including inhibitory control, working memory, and cognitive flexibility, develop gradually throughout childhood and adolescence, influencing academic achievement and social competence.

Cognitive neuroscience has revolutionized cognitive psychology by providing direct measures of brain activity during cognitive tasks. Neuroimaging techniques, including functional magnetic resonance imaging (fMRI), positron emission tomography (PET), and electroencephalography (EEG), enable researchers to observe neural correlates of mental processes in real-time. These methodologies have validated many cognitive theories while revealing unexpected brain-behavior relationships and identifying neural networks supporting specific cognitive functions.

The practical applications of cognitive psychology extend across numerous domains, informing educational practices, clinical interventions, and technology design. Cognitive load theory guides instructional design by considering limitations in working memory capacity, while spaced repetition and elaborative processing techniques optimize learning efficiency. Clinical applications include cognitive-behavioral therapy approaches that modify maladaptive thought patterns and cognitive rehabilitation programs for individuals with brain injuries or neurological conditions.

Human-computer interaction research applies cognitive principles to design user-friendly interfaces that accommodate human information processing limitations and capabilities. Understanding attention, memory, and decision-making processes enables designers to create intuitive systems that reduce cognitive burden while maximizing user performance and satisfaction.

Contemporary cognitive psychology continues to evolve through integration with other disciplines, including neuroscience, computer science, linguistics, and philosophy of mind. Emerging areas of investigation include embodied cognition, which emphasizes the role of physical experience in shaping thought processes, and situated cognition, which examines how environmental contexts influence cognitive performance. As technology advances and research methodologies become more sophisticated, cognitive psychology promises to yield increasingly detailed understanding of the remarkable complexity and adaptability of human cognition.`,
            audioUrl: null,
            listeningScript: null
        },
        {
            testId: 35,
            partNumber: 3,
            title: 'Reading Passage 3',
            instructions: 'You should spend about 20 minutes on Questions 28-40, which are based on Reading Passage 3 below.',
            content: `Urban Planning: Creating Sustainable Cities for the Future

Urban planning has evolved from a primarily aesthetic and regulatory discipline into a comprehensive approach for creating sustainable, equitable, and resilient cities that can accommodate growing populations while minimizing environmental impact. As urbanization accelerates globally, with more than half of the world's population now living in cities and projections indicating that urban areas will house nearly 70% of humanity by 2050, the role of thoughtful urban planning becomes increasingly critical for addressing challenges related to housing, transportation, infrastructure, environmental quality, and social equity.

The history of modern urban planning traces back to the Industrial Revolution, when rapid urban growth and poor living conditions prompted reformers to advocate for systematic approaches to city development. Visionary planners like Baron Haussmann in Paris and Daniel Burnham in Chicago demonstrated how comprehensive planning could transform urban environments, creating grand boulevards, public parks, and civic buildings that improved both functionality and aesthetic appeal. The Garden City movement, initiated by Ebenezer Howard in England, proposed integrating urban and rural elements to create healthier, more livable communities surrounded by greenbelts.

Contemporary urban planning embraces principles of sustainability, recognizing that cities consume approximately 78% of global energy and produce more than 60% of greenhouse gas emissions despite occupying only 2% of the Earth's land surface. Sustainable urban development strategies focus on reducing resource consumption, minimizing waste generation, and creating compact, mixed-use neighborhoods that reduce transportation needs and promote walkability. Green building standards and energy-efficient infrastructure contribute to environmental sustainability while often providing economic benefits through reduced operating costs.

Transit-oriented development represents a cornerstone of sustainable urban planning, concentrating higher-density residential and commercial development around public transportation nodes to reduce automobile dependence and promote sustainable mobility options. Cities implementing transit-oriented development strategies typically experience reduced traffic congestion, improved air quality, and enhanced economic vitality in areas surrounding transit stations. Successful examples include Copenhagen's bicycle infrastructure network, which accommodates over 40% of commuter trips, and Curitiba's bus rapid transit system, which serves as a model for efficient public transportation in developing cities.

Smart growth principles guide urban expansion by promoting infill development, brownfield redevelopment, and urban boundary controls that prevent sprawl and preserve agricultural land and natural areas. These strategies encourage efficient land use patterns that support public transit, reduce infrastructure costs, and maintain community character while accommodating population growth. Mixed-use development integrates residential, commercial, and office spaces within walkable neighborhoods, reducing travel distances and creating vibrant, diverse communities.

Green infrastructure incorporates natural systems into urban environments to provide essential services including stormwater management, air purification, temperature regulation, and habitat creation. Urban forests, green roofs, constructed wetlands, and permeable pavements help cities manage environmental challenges while enhancing quality of life for residents. Singapore's "City in a Garden" vision demonstrates how extensive green infrastructure can coexist with high-density development, achieving remarkable biodiversity conservation within an urban context.

Affordable housing represents one of urban planning's most persistent challenges, as rising property values and gentrification often displace low-income residents from central urban areas. Inclusionary zoning policies require new developments to include affordable housing units, while community land trusts and social housing programs provide alternative ownership models that maintain long-term affordability. Vienna's social housing program, serving approximately 60% of the city's population, demonstrates how public investment in housing can create high-quality, affordable communities while promoting social integration.

Participatory planning processes engage community members in decision-making, ensuring that urban development reflects local needs, preferences, and cultural values. Public consultations, community workshops, and citizen advisory committees provide forums for resident input, while digital platforms and mobile applications enable broader participation in planning processes. Co-design approaches involve community members as active partners in creating solutions, fostering local ownership and support for planning initiatives.

Climate adaptation planning addresses the increasing risks cities face from climate change, including extreme weather events, sea-level rise, and temperature increases. Resilient infrastructure design incorporates flexibility and redundancy to withstand disruptions, while early warning systems and emergency preparedness programs protect vulnerable populations. Rotterdam's comprehensive flood protection system, including water plazas that serve recreational functions during dry periods and stormwater management during heavy rainfall, exemplifies innovative climate adaptation strategies.

Data-driven planning utilizes geographic information systems (GIS), remote sensing, and big data analytics to inform decision-making and monitor urban conditions. Real-time data on traffic patterns, air quality, energy consumption, and population movement enable responsive management of urban systems and evidence-based policy development. Smart city technologies, including sensor networks and Internet of Things (IoT) devices, provide continuous monitoring capabilities that support adaptive urban management.

Economic development strategies in urban planning focus on creating diverse, knowledge-based economies that provide opportunities for residents across skill levels. Innovation districts cluster research institutions, startup companies, and established businesses to foster entrepreneurship and technology transfer. Creative districts leverage arts, culture, and design industries to drive economic growth while contributing to urban vitality and identity.

Public space design plays a crucial role in urban quality of life, providing venues for social interaction, recreation, and cultural expression. Well-designed parks, plazas, and streetscapes contribute to community cohesion, physical and mental health, and economic vitality. The High Line in New York City demonstrates how innovative adaptive reuse can transform abandoned infrastructure into beloved public spaces that catalyze neighborhood revitalization.

Regional planning coordination addresses challenges that transcend municipal boundaries, including transportation networks, watershed management, and economic development. Metropolitan planning organizations facilitate cooperation among multiple jurisdictions, developing integrated strategies for sustainable regional growth. The Portland metropolitan region's urban growth boundary system demonstrates how regional coordination can manage growth while preserving natural areas and agricultural land.

Future directions in urban planning increasingly emphasize flexibility and adaptability in the face of rapid technological, social, and environmental change. Tactical urbanism employs temporary, low-cost interventions to test planning concepts and engage communities in place-making activities. Scenario planning helps cities prepare for multiple possible futures by developing adaptive strategies that can respond to different demographic, economic, and environmental conditions.

As urban populations continue to grow and climate challenges intensify, the importance of innovative, sustainable urban planning approaches becomes ever more critical. Success will require integration of environmental, social, and economic considerations, meaningful community engagement, and adaptive management strategies that can respond to changing conditions while maintaining focus on creating livable, equitable, and resilient urban environments for all residents.`
        }
    ];

    const test35Questions = [
        // Part 1 Questions (1-13)
        { partId: 4, questionNumber: 1, questionText: 'Solar electricity costs have declined by approximately 85% since 2010.', questionType: 'true_false_not_given', options: null, correctAnswer: 'TRUE', marks: 1 },
        { partId: 4, questionNumber: 2, questionText: 'Offshore wind farms are more expensive than onshore installations.', questionType: 'true_false_not_given', options: null, correctAnswer: 'NOT GIVEN', marks: 1 },
        { partId: 4, questionNumber: 3, questionText: 'Modern wind turbines can be up to _______ meters tall.', questionType: 'gap_fill', options: null, correctAnswer: '150', marks: 1 },
        { partId: 4, questionNumber: 4, questionText: 'Hydroelectric power generates approximately _______ of global electricity.', questionType: 'gap_fill', options: null, correctAnswer: '16%', marks: 1 },
        { partId: 4, questionNumber: 5, questionText: 'Iceland derives what percentage of its electricity from geothermal sources?', questionType: 'multiple_choice', options: JSON.stringify(['A) 15%', 'B) 25%', 'C) 35%', 'D) 45%']), correctAnswer: 'B', marks: 1 },
        { partId: 4, questionNumber: 6, questionText: 'Iceland gets _______ of its heating from geothermal sources.', questionType: 'gap_fill', options: null, correctAnswer: '90%', marks: 1 },
        { partId: 4, questionNumber: 7, questionText: 'Biomass energy can be derived from agricultural waste and forestry _______.', questionType: 'gap_fill', options: null, correctAnswer: 'residues', marks: 1 },
        { partId: 4, questionNumber: 8, questionText: 'Which type of battery has experienced dramatic cost reductions?', questionType: 'multiple_choice', options: JSON.stringify(['A) Lead-acid', 'B) Nickel-cadmium', 'C) Lithium-ion', 'D) Sodium-sulfur']), correctAnswer: 'C', marks: 1 },
        { partId: 4, questionNumber: 9, questionText: 'Smart grid technologies enable _______ communication between generators and consumers.', questionType: 'gap_fill', options: null, correctAnswer: 'bidirectional', marks: 1 },
        { partId: 4, questionNumber: 10, questionText: 'Demand response programs encourage consumers to adjust electricity _______ patterns.', questionType: 'gap_fill', options: null, correctAnswer: 'usage', marks: 1 },
        { partId: 4, questionNumber: 11, questionText: 'The renewable energy sector employs millions of workers globally.', questionType: 'true_false_not_given', options: null, correctAnswer: 'TRUE', marks: 1 },
        { partId: 4, questionNumber: 12, questionText: 'All developing countries have equal access to renewable energy technologies.', questionType: 'true_false_not_given', options: null, correctAnswer: 'FALSE', marks: 1 },
        { partId: 4, questionNumber: 13, questionText: 'Emerging technologies mentioned include perovskite solar cells and floating _______ wind platforms.', questionType: 'gap_fill', options: null, correctAnswer: 'offshore', marks: 1 },

        // Part 2 Questions (14-27)
        { partId: 5, questionNumber: 14, questionText: 'The cognitive revolution began in the:', questionType: 'multiple_choice', options: JSON.stringify(['A) 1940s', 'B) 1950s', 'C) 1960s', 'D) 1970s']), correctAnswer: 'B', marks: 1 },
        { partId: 5, questionNumber: 15, questionText: 'The modal model of memory was proposed by Atkinson and Shiffrin in _______.', questionType: 'gap_fill', options: null, correctAnswer: '1968', marks: 1 },
        { partId: 5, questionNumber: 16, questionText: 'Short-term memory has a capacity of approximately _______ items.', questionType: 'gap_fill', options: null, correctAnswer: 'seven', marks: 1 },
        { partId: 5, questionNumber: 17, questionText: 'Short-term memory duration is _______ seconds without rehearsal.', questionType: 'gap_fill', options: null, correctAnswer: '15-30', marks: 1 },
        { partId: 5, questionNumber: 18, questionText: 'Who developed the working memory model?', questionType: 'multiple_choice', options: JSON.stringify(['A) George Miller', 'B) Alan Baddeley', 'C) Jerome Bruner', 'D) Ulric Neisser']), correctAnswer: 'B', marks: 1 },
        { partId: 5, questionNumber: 19, questionText: 'The phonological loop processes _______ and acoustic information.', questionType: 'gap_fill', options: null, correctAnswer: 'verbal', marks: 1 },
        { partId: 5, questionNumber: 20, questionText: 'Episodic memory stores personally experienced _______ with temporal details.', questionType: 'gap_fill', options: null, correctAnswer: 'events', marks: 1 },
        { partId: 5, questionNumber: 21, questionText: 'The cocktail party effect demonstrates:', questionType: 'multiple_choice', options: JSON.stringify(['A) Perfect attention filtering', 'B) Imperfect attention filtering', 'C) Complete attention failure', 'D) Attention enhancement']), correctAnswer: 'B', marks: 1 },
        { partId: 5, questionNumber: 22, questionText: 'Heuristics and biases research was pioneered by Daniel Kahneman and _______.', questionType: 'gap_fill', options: null, correctAnswer: 'Amos Tversky', marks: 1 },
        { partId: 5, questionNumber: 23, questionText: 'Jean Piaget influenced cognitive _______ research.', questionType: 'gap_fill', options: null, correctAnswer: 'development', marks: 1 },
        { partId: 5, questionNumber: 24, questionText: 'Which neuroimaging technique is mentioned first in the passage?', questionType: 'multiple_choice', options: JSON.stringify(['A) PET', 'B) EEG', 'C) fMRI', 'D) MRI']), correctAnswer: 'C', marks: 1 },
        { partId: 5, questionNumber: 25, questionText: 'Cognitive load theory guides _______ design.', questionType: 'gap_fill', options: null, correctAnswer: 'instructional', marks: 1 },
        { partId: 5, questionNumber: 26, questionText: 'Embodied cognition emphasizes the role of _______ experience in thought.', questionType: 'gap_fill', options: null, correctAnswer: 'physical', marks: 1 },
        { partId: 5, questionNumber: 27, questionText: 'Situated cognition examines how _______ contexts influence cognitive performance.', questionType: 'gap_fill', options: null, correctAnswer: 'environmental', marks: 1 },

        // Part 3 Questions (28-40)
        { partId: 6, questionNumber: 28, questionText: 'By 2050, what percentage of humanity is projected to live in urban areas?', questionType: 'multiple_choice', options: JSON.stringify(['A) 60%', 'B) 65%', 'C) 70%', 'D) 75%']), correctAnswer: 'C', marks: 1 },
        { partId: 6, questionNumber: 29, questionText: 'Cities consume approximately _______ of global energy.', questionType: 'gap_fill', options: null, correctAnswer: '78%', marks: 1 },
        { partId: 6, questionNumber: 30, questionText: 'Cities produce more than _______ of greenhouse gas emissions.', questionType: 'gap_fill', options: null, correctAnswer: '60%', marks: 1 },
        { partId: 6, questionNumber: 31, questionText: 'Cities occupy only _______ of the Earth\'s land surface.', questionType: 'gap_fill', options: null, correctAnswer: '2%', marks: 1 },
        { partId: 6, questionNumber: 32, questionText: 'In Copenhagen, what percentage of commuter trips use bicycle infrastructure?', questionType: 'multiple_choice', options: JSON.stringify(['A) 30%', 'B) 35%', 'C) 40%', 'D) 45%']), correctAnswer: 'C', marks: 1 },
        { partId: 6, questionNumber: 33, questionText: 'Singapore\'s urban vision is called "City in a _______".', questionType: 'gap_fill', options: null, correctAnswer: 'Garden', marks: 1 },
        { partId: 6, questionNumber: 34, questionText: 'Vienna\'s social housing program serves approximately _______ of the city\'s population.', questionType: 'gap_fill', options: null, correctAnswer: '60%', marks: 1 },
        { partId: 6, questionNumber: 35, questionText: 'Which city is mentioned as an example of innovative flood protection?', questionType: 'multiple_choice', options: JSON.stringify(['A) Amsterdam', 'B) Rotterdam', 'C) Copenhagen', 'D) Venice']), correctAnswer: 'B', marks: 1 },
        { partId: 6, questionNumber: 36, questionText: 'Data-driven planning utilizes GIS and _______ sensing technologies.', questionType: 'gap_fill', options: null, correctAnswer: 'remote', marks: 1 },
        { partId: 6, questionNumber: 37, questionText: 'Innovation districts cluster research institutions and _______ companies.', questionType: 'gap_fill', options: null, correctAnswer: 'startup', marks: 1 },
        { partId: 6, questionNumber: 38, questionText: 'The High Line is located in:', questionType: 'multiple_choice', options: JSON.stringify(['A) Boston', 'B) Chicago', 'C) New York City', 'D) Philadelphia']), correctAnswer: 'C', marks: 1 },
        { partId: 6, questionNumber: 39, questionText: 'Tactical urbanism employs temporary, _______-cost interventions.', questionType: 'gap_fill', options: null, correctAnswer: 'low', marks: 1 },
        { partId: 6, questionNumber: 40, questionText: 'Future urban planning emphasizes _______ and adaptability.', questionType: 'gap_fill', options: null, correctAnswer: 'flexibility', marks: 1 }
    ];

    // Test 36 - IELTS Reading Practice Test 3
    const test36Parts = [
        {
            testId: 36,
            partNumber: 1,
            title: 'Reading Passage 1',
            instructions: 'You should spend about 20 minutes on Questions 1-13, which are based on Reading Passage 1 below.',
            content: `Marine Biology: Exploring the Mysteries of Ocean Life

Marine biology encompasses the scientific study of organisms inhabiting oceanic environments, from microscopic plankton to massive whales, revealing the extraordinary diversity and complexity of life beneath the waves. The world's oceans, covering approximately 71% of Earth's surface and containing 97% of the planet's water, harbor ecosystems of unprecedented richness and ecological importance. As technological advances enable deeper exploration of marine environments, scientists continue to discover new species, uncover intricate ecological relationships, and gain insights into the fundamental processes that sustain life in aquatic systems.

The marine environment presents unique challenges and opportunities that have shaped the evolution of remarkable adaptations among ocean-dwelling organisms. Pressure increases dramatically with depth, reaching over 1,000 times atmospheric pressure in the deepest ocean trenches, while temperature decreases and light penetration diminishes rapidly beyond the surface layers. These extreme conditions have led to extraordinary physiological and behavioral adaptations, including bioluminescence, specialized pressure-resistant proteins, and unique reproductive strategies that enable survival in one of Earth's most demanding environments.

Coral reefs represent among the most biodiverse ecosystems on the planet, supporting approximately 25% of all marine species despite occupying less than 1% of ocean area. The symbiotic relationship between coral polyps and zooxanthellae algae forms the foundation of reef ecosystems, with algae providing photosynthetic energy while corals offer protection and nutrients. This partnership enables reef-building corals to construct massive calcium carbonate structures that provide habitat for countless fish species, invertebrates, and marine plants. The Great Barrier Reef, stretching over 2,300 kilometers along Australia's coast, exemplifies the scale and complexity of coral reef systems.

Ocean productivity depends largely on phytoplankton, microscopic photosynthetic organisms that form the base of marine food webs while producing approximately 50% of Earth's oxygen. These tiny organisms, including diatoms, dinoflagellates, and cyanobacteria, convert sunlight and carbon dioxide into organic matter through photosynthesis, supporting entire marine ecosystems. Seasonal and regional variations in phytoplankton abundance influence fish populations, marine mammal distributions, and global climate patterns through their role in carbon cycling and atmospheric gas exchange.

Deep-sea environments, representing Earth's largest habitat by volume, remain among the least explored regions on the planet. The abyssal plains, hydrothermal vents, and cold seeps of the deep ocean support unique communities of organisms adapted to life without sunlight. Chemosynthetic bacteria at hydrothermal vents convert chemical energy from volcanic activity into organic compounds, supporting remarkable ecosystems including giant tube worms, ghostly white crabs, and specialized fish species found nowhere else on Earth. These discoveries have revolutionized understanding of life's limits and possibilities.

Marine mammals demonstrate remarkable adaptations for aquatic life, having evolved from terrestrial ancestors through millions of years of evolutionary change. Whales, dolphins, seals, and manatees exhibit sophisticated echolocation abilities, streamlined body forms, specialized breathing adaptations, and complex social behaviors that enable success in marine environments. Blue whales, the largest animals ever known to exist, can reach lengths exceeding 30 meters and weights of over 200 tons, feeding almost exclusively on tiny krill through efficient filter-feeding mechanisms.

Fish diversity in marine environments exceeds that of any other vertebrate group, with over 15,000 described species exhibiting extraordinary variety in size, shape, behavior, and ecological roles. From tiny gobies measuring less than a centimeter to massive whale sharks reaching 18 meters in length, marine fish have evolved to exploit virtually every available niche in ocean ecosystems. Schooling behaviors, migration patterns, and reproductive strategies demonstrate complex adaptations that maximize survival and reproductive success in dynamic marine environments.

Marine conservation faces unprecedented challenges as human activities increasingly impact ocean ecosystems through pollution, overfishing, habitat destruction, and climate change. Plastic pollution affects marine life throughout the food web, from microscopic organisms ingesting microplastics to large marine animals becoming entangled in discarded fishing gear. Ocean acidification, resulting from increased atmospheric carbon dioxide absorption, threatens calcium carbonate-dependent organisms including corals, mollusks, and certain plankton species essential to marine food webs.

Overfishing has depleted many commercially important fish populations, with some species experiencing population declines exceeding 90% from historical levels. Industrial fishing methods, including bottom trawling and long-line fishing, cause significant habitat damage and bycatch mortality, affecting non-target species including dolphins, sea turtles, and seabirds. Sustainable fisheries management requires comprehensive approaches incorporating scientific assessment, regulatory frameworks, and international cooperation to ensure long-term ocean productivity.

Climate change impacts on marine ecosystems include rising sea temperatures, changing current patterns, sea level rise, and altered precipitation affecting coastal habitats. Coral bleaching events, triggered by elevated water temperatures, have caused widespread mortality in reef systems worldwide. Range shifts in marine species distributions disrupt established ecological relationships and affect fisheries productivity, while melting polar ice alters habitat availability for ice-dependent species including polar bears, seals, and Arctic cod.

Marine protected areas serve as essential tools for ocean conservation, providing refuges where marine life can recover from human pressures while maintaining genetic diversity and ecosystem functions. Successful marine reserves demonstrate rapid recovery of fish populations, increased biodiversity, and spillover effects that benefit surrounding areas. The Papahānaumokuākea Marine National Monument, encompassing 1.5 million square kilometers in the Pacific Ocean, represents one of the world's largest marine protected areas, safeguarding pristine coral reefs and critical habitat for endangered species.

Technological advances continue to expand our capacity for marine exploration and research. Remotely operated vehicles (ROVs), autonomous underwater vehicles (AUVs), and advanced diving systems enable scientists to study previously inaccessible deep-sea environments. Satellite technology provides unprecedented views of ocean surface conditions, tracking algal blooms, temperature patterns, and marine animal movements across vast spatial scales. Genetic techniques reveal hidden biodiversity and evolutionary relationships among marine organisms, while acoustic monitoring systems track whale migrations and communication patterns.

The future of marine biology research promises continued discoveries as exploration technologies advance and new analytical techniques emerge. Environmental DNA sampling allows detection of species presence from water samples, revolutionizing biodiversity surveys and monitoring programs. Citizen science initiatives engage recreational divers, fishers, and coastal communities in data collection, expanding research capacity while building public awareness of marine conservation needs. As human populations grow and climate change accelerates, the importance of understanding and protecting marine ecosystems becomes increasingly critical for planetary health and human wellbeing.`,
            audioUrl: null,
            listeningScript: null
        },
        {
            testId: 36,
            partNumber: 2,
            title: 'Reading Passage 2',
            instructions: 'You should spend about 20 minutes on Questions 14-27, which are based on Reading Passage 2 below.',
            content: `Digital Technology: Transforming Society in the Information Age

The rapid advancement of digital technology has fundamentally transformed virtually every aspect of human society, creating unprecedented opportunities for communication, commerce, education, and creative expression while simultaneously presenting complex challenges related to privacy, security, inequality, and social cohesion. The digital revolution, accelerated by exponential improvements in computing power, data storage capacity, and network connectivity, has reshaped economic structures, social relationships, and individual behaviors in ways that continue to evolve at an extraordinary pace.

The Internet represents perhaps the most transformative technological development of the modern era, connecting billions of people worldwide and enabling instantaneous global communication and information sharing. From its origins as a research network connecting universities and government institutions, the Internet has evolved into a vast, decentralized system supporting everything from social media platforms and e-commerce sites to streaming services and cloud computing infrastructure. The World Wide Web, invented by Tim Berners-Lee in 1989, democratized access to information and created platforms for user-generated content that have revolutionized media, education, and social interaction.

Mobile technology has extended digital connectivity beyond traditional computer systems, putting powerful computing capabilities into the hands of users everywhere. Smartphones, combining communication, computing, and multimedia capabilities in portable devices, have become essential tools for modern life, enabling mobile banking, navigation, photography, and access to vast libraries of information and entertainment. The proliferation of mobile devices has driven development of mobile-first applications and services while creating new challenges related to digital addiction, privacy, and social behavior.

Social media platforms have fundamentally altered how people communicate, share information, and form relationships, creating global communities around shared interests while enabling unprecedented levels of social connectivity. Facebook, Twitter, Instagram, LinkedIn, and other platforms facilitate instant communication among friends, family members, and professional networks, while providing forums for public discourse, political engagement, and cultural exchange. However, social media has also contributed to information polarization, cyberbullying, and concerns about mental health impacts, particularly among young users.

E-commerce has revolutionized retail and business operations, enabling companies to reach global markets while providing consumers with unprecedented convenience and choice. Online marketplaces like Amazon, Alibaba, and eBay have transformed shopping behaviors and supply chain management, while digital payment systems including PayPal, mobile wallets, and cryptocurrency have created new financial transaction methods. The COVID-19 pandemic accelerated e-commerce adoption, with many businesses rapidly transitioning to online sales and service delivery models.

Artificial intelligence and machine learning technologies are increasingly integrated into digital systems, enabling automation of complex tasks and personalization of user experiences. AI applications include recommendation systems that suggest content and products, virtual assistants that respond to voice commands, autonomous vehicles that navigate without human intervention, and medical diagnostic systems that analyze patient data. Machine learning algorithms process vast amounts of data to identify patterns and make predictions, supporting everything from financial trading to climate modeling.

Big data analytics has emerged as a critical capability for organizations seeking to understand customer behavior, optimize operations, and identify new opportunities. The ability to collect, store, and analyze massive datasets enables companies to personalize marketing messages, improve product designs, and predict consumer preferences with unprecedented accuracy. Data analytics drives decision-making in sectors ranging from healthcare and education to transportation and urban planning, while raising important questions about data ownership, privacy, and algorithmic bias.

Cloud computing has fundamentally changed how organizations manage information technology resources, enabling on-demand access to computing power, storage, and software applications through Internet-based services. Cloud platforms provided by companies like Amazon Web Services, Microsoft Azure, and Google Cloud allow businesses to scale their technology infrastructure rapidly while reducing capital investments and operational complexity. This shift has enabled small companies to access enterprise-level capabilities while supporting the development of innovative applications and services.

The Internet of Things (IoT) connects everyday objects to digital networks, creating smart homes, cities, and industrial systems that can monitor conditions and respond automatically to changing circumstances. Smart thermostats, security cameras, automotive systems, and wearable devices collect data and provide remote control capabilities, while industrial IoT applications optimize manufacturing processes and supply chain management. However, the proliferation of connected devices also creates new security vulnerabilities and privacy concerns.

Cybersecurity has become a critical concern as digital systems become increasingly central to economic and social infrastructure. Cyberattacks, including data breaches, ransomware, and system intrusions, threaten individual privacy, corporate operations, and national security. The sophistication of cyber threats continues to evolve, requiring constant adaptation of security measures and international cooperation to address criminal activities that transcend national boundaries.

Digital divide issues persist as not all populations have equal access to digital technologies and the opportunities they provide. Rural communities, elderly individuals, and low-income households often face barriers related to infrastructure availability, device costs, and digital literacy skills. These disparities can exacerbate existing social and economic inequalities, making efforts to expand digital access and education increasingly important for social equity.

Privacy concerns have intensified as digital technologies enable unprecedented collection and analysis of personal information. Data collection practices by technology companies, government surveillance programs, and the commercialization of personal data have sparked debates about individual privacy rights and the need for regulatory frameworks to protect user information. The European Union's General Data Protection Regulation (GDPR) represents one effort to establish stronger privacy protections in the digital age.

Remote work and digital collaboration tools have transformed employment patterns and workplace dynamics, particularly accelerated by the COVID-19 pandemic. Video conferencing, project management platforms, and cloud-based productivity tools enable employees to work effectively from diverse locations while maintaining team collaboration and organizational productivity. This shift has implications for urban planning, commercial real estate, and work-life balance while creating new opportunities for global talent access.

Educational technology has expanded access to learning opportunities while enabling personalized instruction and assessment. Online courses, educational apps, and virtual reality systems provide innovative ways to deliver educational content and engage learners, while learning management systems facilitate distance education and blended learning approaches. However, the digital divide affects educational equity, and concerns about screen time and social interaction influence debates about technology's role in education.

The future of digital technology promises continued innovation through emerging technologies including quantum computing, augmented reality, blockchain systems, and advanced artificial intelligence. These developments will likely create new opportunities while presenting fresh challenges related to ethics, regulation, and social adaptation. As digital technologies become increasingly integrated into all aspects of life, society must navigate complex tradeoffs between innovation and stability, efficiency and equity, connectivity and privacy.`,
            audioUrl: null,
            listeningScript: null
        },
        {
            testId: 36,
            partNumber: 3,
            title: 'Reading Passage 3',
            instructions: 'You should spend about 20 minutes on Questions 28-40, which are based on Reading Passage 3 below.',
            content: `Archaeological Research: Uncovering Humanity's Hidden Past

Archaeological research serves as humanity's primary window into prehistoric and ancient civilizations, employing sophisticated scientific methodologies to reconstruct past cultures, technologies, and social systems from material remains buried beneath millennia of sediment and debris. This multidisciplinary field combines elements of anthropology, history, geology, chemistry, and biology to interpret artifacts, structures, and environmental evidence that illuminate how our ancestors lived, worked, and organized their societies. Modern archaeological practice has evolved far beyond treasure hunting and artifact collection to become a rigorous scientific discipline that provides crucial insights into human cultural evolution and adaptation.

The theoretical foundations of contemporary archaeology emphasize systematic excavation, careful documentation, and interdisciplinary analysis of archaeological sites and materials. Stratigraphic excavation techniques, develope